@startuml
left to right direction

actor Користувач as U

rectangle "Password Manager" {
  usecase "Додати запис" as UC1
  usecase "Переглянути записи" as UC2
  usecase "Пошук запису" as UC3
  usecase "Редагувати запис" as UC4
  usecase "Видалити запис" as UC5
  usecase "Сортувати записи" as UC6
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6

@enduml